from typing import Any

class Validator:
    def __init__(self, *names: str, **kwargs: Any) -> None: ...

class _Validators:
    def validate(self) -> None: ...

class Dynaconf:
    validators: _Validators

    def __init__(self, **kwargs: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
